import { UserRole } from '@/types/auth';

export enum ActivityEventType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  EMAIL_CHANGE_REQUESTED = 'EMAIL_CHANGE_REQUESTED',
  EMAIL_CHANGE_FAILED = 'EMAIL_CHANGE_FAILED',
  EMAIL_CHANGE_COMPLETED = 'EMAIL_CHANGE_COMPLETED',
  EMAIL_VERIFICATION_REQUESTED = 'EMAIL_VERIFICATION_REQUESTED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  TWO_FACTOR_ENABLED = 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED = 'TWO_FACTOR_DISABLED',
  ACCOUNT_RECOVERY_REQUESTED = 'ACCOUNT_RECOVERY_REQUESTED',
  ACCOUNT_RECOVERY_COMPLETED = 'ACCOUNT_RECOVERY_COMPLETED',
  ACCOUNT_RECOVERY_FAILED = 'ACCOUNT_RECOVERY_FAILED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  TEST_CASE_CREATED = 'TEST_CASE_CREATED',
  TEST_CASE_UPDATED = 'TEST_CASE_UPDATED',
  TEST_CASE_DELETED = 'TEST_CASE_DELETED',
  TEST_RUN_STARTED = 'TEST_RUN_STARTED',
  TEST_RUN_COMPLETED = 'TEST_RUN_COMPLETED',
  TEST_RUN_CANCELLED = 'TEST_RUN_CANCELLED',
  FAILED_LOGIN_ATTEMPT = 'FAILED_LOGIN_ATTEMPT',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY'
}

export interface ActivityLogEntry {
  type: ActivityEventType;
  userId: string;
  details: {
    targetUserId?: string;
    changes?: {
      [key: string]: {
        from: unknown;
        to: unknown;
      };
    };
    metadata?: Record<string, unknown>;
  };
  context?: ActivityContext;
}

export interface ActivityContext {
  ip?: string;
  userAgent?: string;
  location?: string;
} 