export const TEST_RESULT_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED'
} as const;

export type TestResultStatus = typeof TEST_RESULT_STATUS[keyof typeof TEST_RESULT_STATUS];

export const TEST_RUN_ERROR_CODES = {
  EXECUTION_ERROR: 'EXECUTION_ERROR',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_TEST_CASES: 'INVALID_TEST_CASES',
  NOT_FOUND: 'NOT_FOUND',
  COMPLETION_ERROR: 'COMPLETION_ERROR'
} as const;

export type TestRunErrorCode = typeof TEST_RUN_ERROR_CODES[keyof typeof TEST_RUN_ERROR_CODES]; 